### ISSUE TITLE
i got error with module 

### ISSUE THREAD

**Issue by h9zdev** [arun-arunisto/ComputerVisionEngineering#1]
Traceback (most recent call last):
  File "/home/digitalmycelia/Desktop/OpenCVTutorial/ai_virtual_mouse.py", line 4, in <module>
    from handTrackingModule import handDetector
ModuleNotFoundError: No module named 'handTrackingModule'

**Comment by arun-arunisto** [comment]
its a module created by me with using hand tracking basics file, if anyone want that my file contact me i will send you personally!!
